---
#ci.gocd.yaml
# See: https://github.com/tomzo/gocd-yaml-config-plugin
format_version: 2
pipelines:

  shared-dns:
    group: ops-shared
    label_template: "${mygit[:8]}"
    lock_behavior: unlockWhenFinished
    materials:
      mygit:
        git: https://github.com/packetfield/infra-core.git
        branch: developer

    timer:
      spec: "0 0 11 ? * MON-FRI"  #mon-fri 11AM (office hours)
    stages:
      - deps:
          clean_workspace: false
          jobs:
            deps:
              tasks:
               - exec:
                   command: /bin/bash
                   arguments:
                    - bin/gocd-helper
                    - deps
      - apply:
          clean_workspace: false
          jobs:
            apply:
              tasks:
               - exec:
                   command: /bin/bash
                   arguments:
                    - bin/gocd-helper
                    - make
                    - ENV=shared
                    - COMPONENT=dns
                    - plan





  shared-drone:
    group: ops-shared
    label_template: "${mygit[:8]}"
    lock_behavior: unlockWhenFinished
    materials:
      mygit:
        git: https://github.com/packetfield/infra-core.git
        branch: developer

    timer:
      spec: "0 0 11 ? * MON-FRI"  #mon-fri 11AM (office hours)
    stages:
      - deps:
          clean_workspace: false
          jobs:
            deps:
              tasks:
               - exec:
                   command: /bin/bash
                   arguments:
                    - bin/gocd-helper
                    - deps
      - apply:
          clean_workspace: false
          jobs:
            apply:
              tasks:
               - exec:
                   command: /bin/bash
                   arguments:
                    - bin/gocd-helper
                    - make
                    - ENV=shared
                    - COMPONENT=drone
                    - plan


      - config:
          clean_workspace: false
          jobs:
            config:
              tasks:
               - exec:
                   command: /bin/bash
                   arguments:
                    - bin/gocd-helper
                    - make
                    - ENV=shared
                    - COMPONENT=drone
                    - config




  shared-gocd:
    group: ops-shared
    label_template: "${mygit[:8]}"
    lock_behavior: unlockWhenFinished
    materials:
      mygit:
        git: https://github.com/packetfield/infra-core.git
        branch: developer

    timer:
      spec: "0 0 11 ? * MON-FRI"  #mon-fri 11AM (office hours)
    stages:
      - deps:
          clean_workspace: false
          jobs:
            deps:
              tasks:
               - exec:
                   command: /bin/bash
                   arguments:
                    - bin/gocd-helper
                    - deps
      - apply:
          clean_workspace: false
          jobs:
            apply:
              tasks:
               - exec:
                   command: /bin/bash
                   arguments:
                    - bin/gocd-helper
                    - make
                    - ENV=shared
                    - COMPONENT=gocd
                    - plan


      - config:
          clean_workspace: false
          jobs:
            config:
              tasks:
               - exec:
                   command: /bin/bash
                   arguments:
                    - bin/gocd-helper
                    - make
                    - ENV=shared
                    - COMPONENT=gocd
                    - config




  develop-prometheus:
    group: ops-develop
    label_template: "${mygit[:8]}"
    lock_behavior: unlockWhenFinished
    materials:
      mygit:
        git: https://github.com/packetfield/infra-core.git
        branch: develop

    timer:
      spec: "0 0 11 ? * MON-FRI"  #mon-fri 11AM (office hours)
    stages:
      - deps:
          clean_workspace: false
          jobs:
            deps:
              tasks:
               - exec:
                   command: /bin/bash
                   arguments:
                    - bin/gocd-helper
                    - deps
      - apply:
          clean_workspace: false
          jobs:
            apply:
              tasks:
               - exec:
                   command: /bin/bash
                   arguments:
                    - bin/gocd-helper
                    - make
                    - ENV=develop
                    - COMPONENT=prometheus
                    - plan





  develop-dns:
    group: ops-develop
    label_template: "${mygit[:8]}"
    lock_behavior: unlockWhenFinished
    materials:
      mygit:
        git: https://github.com/packetfield/infra-core.git
        branch: develop

    timer:
      spec: "0 0 11 ? * MON-FRI"  #mon-fri 11AM (office hours)
    stages:
      - deps:
          clean_workspace: false
          jobs:
            deps:
              tasks:
               - exec:
                   command: /bin/bash
                   arguments:
                    - bin/gocd-helper
                    - deps
      - apply:
          clean_workspace: false
          jobs:
            apply:
              tasks:
               - exec:
                   command: /bin/bash
                   arguments:
                    - bin/gocd-helper
                    - make
                    - ENV=develop
                    - COMPONENT=dns
                    - plan





  master-prometheus:
    group: ops-master
    label_template: "${mygit[:8]}"
    lock_behavior: unlockWhenFinished
    materials:
      mygit:
        git: https://github.com/packetfield/infra-core.git
        branch: master

    timer:
      spec: "0 0 11 ? * MON-FRI"  #mon-fri 11AM (office hours)
    stages:
      - deps:
          clean_workspace: false
          jobs:
            deps:
              tasks:
               - exec:
                   command: /bin/bash
                   arguments:
                    - bin/gocd-helper
                    - deps
      - apply:
          clean_workspace: false
          jobs:
            apply:
              tasks:
               - exec:
                   command: /bin/bash
                   arguments:
                    - bin/gocd-helper
                    - make
                    - ENV=master
                    - COMPONENT=prometheus
                    - plan





  master-dns:
    group: ops-master
    label_template: "${mygit[:8]}"
    lock_behavior: unlockWhenFinished
    materials:
      mygit:
        git: https://github.com/packetfield/infra-core.git
        branch: master

    timer:
      spec: "0 0 11 ? * MON-FRI"  #mon-fri 11AM (office hours)
    stages:
      - deps:
          clean_workspace: false
          jobs:
            deps:
              tasks:
               - exec:
                   command: /bin/bash
                   arguments:
                    - bin/gocd-helper
                    - deps
      - apply:
          clean_workspace: false
          jobs:
            apply:
              tasks:
               - exec:
                   command: /bin/bash
                   arguments:
                    - bin/gocd-helper
                    - make
                    - ENV=master
                    - COMPONENT=dns
                    - plan




